// Generated from the canonical PostgreSQL 16 schema.
// Run `npm run database:types:generate`; do not edit this file manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      "agent_artifacts": {
        Row: {
          "id": string
          "task_id": string
          "user_id": string
          "kind": string
          "title": string | null
          "content": string | null
          "url": string | null
          "meta": Json | null
          "created_at": string
        }
        Insert: {
          "id"?: string
          "task_id": string
          "user_id": string
          "kind"?: string
          "title"?: string | null
          "content"?: string | null
          "url"?: string | null
          "meta"?: Json | null
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "task_id"?: string
          "user_id"?: string
          "kind"?: string
          "title"?: string | null
          "content"?: string | null
          "url"?: string | null
          "meta"?: Json | null
          "created_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "agent_artifacts_task_id_fkey"
  columns: ["task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "agent_artifacts_tenant_task_fkey"
  columns: ["user_id","task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "agent_confirmation_gates": {
        Row: {
          "id": string
          "task_id": string
          "user_id": string
          "operation": string
          "risk_level": string
          "title": string
          "reason": string
          "files": string[]
          "plan_canonical": string
          "plan_hash": string
          "token_hash": string
          "status": string
          "resume_status": string
          "rejection_reason": string | null
          "created_at": string
          "expires_at": string
          "approved_at": string | null
          "rejected_at": string | null
          "consumed_at": string | null
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "task_id": string
          "user_id": string
          "operation": string
          "risk_level": string
          "title": string
          "reason": string
          "files"?: string[]
          "plan_canonical": string
          "plan_hash": string
          "token_hash": string
          "status"?: string
          "resume_status"?: string
          "rejection_reason"?: string | null
          "created_at"?: string
          "expires_at": string
          "approved_at"?: string | null
          "rejected_at"?: string | null
          "consumed_at"?: string | null
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "task_id"?: string
          "user_id"?: string
          "operation"?: string
          "risk_level"?: string
          "title"?: string
          "reason"?: string
          "files"?: string[]
          "plan_canonical"?: string
          "plan_hash"?: string
          "token_hash"?: string
          "status"?: string
          "resume_status"?: string
          "rejection_reason"?: string | null
          "created_at"?: string
          "expires_at"?: string
          "approved_at"?: string | null
          "rejected_at"?: string | null
          "consumed_at"?: string | null
          "updated_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "agent_confirmation_gates_task_id_fkey"
  columns: ["task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "agent_confirmation_gates_tenant_task_fkey"
  columns: ["user_id","task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "agent_task_steps": {
        Row: {
          "id": string
          "task_id": string
          "user_id": string
          "kind": string
          "label": string | null
          "detail": string | null
          "seq": number
          "created_at": string
        }
        Insert: {
          "id"?: string
          "task_id": string
          "user_id": string
          "kind"?: string
          "label"?: string | null
          "detail"?: string | null
          "seq"?: number
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "task_id"?: string
          "user_id"?: string
          "kind"?: string
          "label"?: string | null
          "detail"?: string | null
          "seq"?: number
          "created_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "agent_task_steps_task_id_fkey"
  columns: ["task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "agent_task_steps_tenant_task_fkey"
  columns: ["user_id","task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "agent_tasks": {
        Row: {
          "id": string
          "user_id": string
          "goal": string
          "mode": string
          "repo": string | null
          "branch": string
          "status": string
          "error": string | null
          "created_at": string
          "updated_at": string
          "started_at": string | null
          "finished_at": string | null
          "meta": Json | null
          "agent_branch": string | null
          "pull_request_url": string | null
          "pull_request_number": number | null
          "commit_sha": string | null
        }
        Insert: {
          "id"?: string
          "user_id": string
          "goal": string
          "mode"?: string
          "repo"?: string | null
          "branch"?: string
          "status"?: string
          "error"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "started_at"?: string | null
          "finished_at"?: string | null
          "meta"?: Json | null
          "agent_branch"?: string | null
          "pull_request_url"?: string | null
          "pull_request_number"?: number | null
          "commit_sha"?: string | null
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "goal"?: string
          "mode"?: string
          "repo"?: string | null
          "branch"?: string
          "status"?: string
          "error"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "started_at"?: string | null
          "finished_at"?: string | null
          "meta"?: Json | null
          "agent_branch"?: string | null
          "pull_request_url"?: string | null
          "pull_request_number"?: number | null
          "commit_sha"?: string | null
        }
        Relationships: []
      },
      "agent_tool_calls": {
        Row: {
          "id": string
          "task_id": string
          "user_id": string
          "step_id": string | null
          "tool_name": string
          "input": Json | null
          "output": Json | null
          "error": string | null
          "status": string
          "started_at": string | null
          "finished_at": string | null
          "duration_ms": number | null
          "seq": number
          "created_at": string
        }
        Insert: {
          "id"?: string
          "task_id": string
          "user_id": string
          "step_id"?: string | null
          "tool_name": string
          "input"?: Json | null
          "output"?: Json | null
          "error"?: string | null
          "status"?: string
          "started_at"?: string | null
          "finished_at"?: string | null
          "duration_ms"?: number | null
          "seq"?: number
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "task_id"?: string
          "user_id"?: string
          "step_id"?: string | null
          "tool_name"?: string
          "input"?: Json | null
          "output"?: Json | null
          "error"?: string | null
          "status"?: string
          "started_at"?: string | null
          "finished_at"?: string | null
          "duration_ms"?: number | null
          "seq"?: number
          "created_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "agent_tool_calls_step_id_fkey"
  columns: ["step_id"]
  isOneToOne: false
  referencedRelation: "agent_task_steps"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "agent_tool_calls_task_id_fkey"
  columns: ["task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "agent_tool_calls_tenant_task_fkey"
  columns: ["user_id","task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["user_id","id"]
},
          {
  foreignKeyName: "agent_tool_calls_tenant_task_step_fkey"
  columns: ["user_id","task_id","step_id"]
  isOneToOne: false
  referencedRelation: "agent_task_steps"
  referencedColumns: ["user_id","task_id","id"]
},
        ]
      },
      "agent_workspace_heads": {
        Row: {
          "task_id": string
          "user_id": string
          "snapshot_id": string
          "manifest_digest": string
          "tree_digest": string
          "head": string
          "version": number
          "job_id": string
          "lease_version": number
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "task_id": string
          "user_id": string
          "snapshot_id": string
          "manifest_digest": string
          "tree_digest": string
          "head": string
          "version"?: number
          "job_id": string
          "lease_version": number
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "task_id"?: string
          "user_id"?: string
          "snapshot_id"?: string
          "manifest_digest"?: string
          "tree_digest"?: string
          "head"?: string
          "version"?: number
          "job_id"?: string
          "lease_version"?: number
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "agent_workspace_heads_job_id_fkey"
  columns: ["job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "agent_workspace_heads_task_id_fkey"
  columns: ["task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "agent_workspace_heads_tenant_job_fkey"
  columns: ["user_id","job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["principal_id","id"]
},
          {
  foreignKeyName: "agent_workspace_heads_tenant_task_fkey"
  columns: ["user_id","task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "agent_workspaces": {
        Row: {
          "id": string
          "task_id": string
          "user_id": string
          "repo": string
          "branch": string
          "commit_sha": string | null
          "path": string | null
          "status": string
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "task_id": string
          "user_id": string
          "repo": string
          "branch"?: string
          "commit_sha"?: string | null
          "path"?: string | null
          "status"?: string
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "task_id"?: string
          "user_id"?: string
          "repo"?: string
          "branch"?: string
          "commit_sha"?: string | null
          "path"?: string | null
          "status"?: string
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "agent_workspaces_task_id_fkey"
  columns: ["task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "agent_workspaces_tenant_task_fkey"
  columns: ["user_id","task_id"]
  isOneToOne: false
  referencedRelation: "agent_tasks"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "api_rate_limits": {
        Row: {
          "key_hash": string
          "request_count": number
          "reset_at": string
          "updated_at": string
        }
        Insert: {
          "key_hash": string
          "request_count": number
          "reset_at": string
          "updated_at"?: string
        }
        Update: {
          "key_hash"?: string
          "request_count"?: number
          "reset_at"?: string
          "updated_at"?: string
        }
        Relationships: []
      },
      "artifacts": {
        Row: {
          "id": string
          "user_id": string
          "conversation_id": string | null
          "title": string
          "html": string | null
          "created_at": string
          "project_id": string | null
          "message_id": string | null
          "raw": string
          "updated_at": string | null
        }
        Insert: {
          "id"?: string
          "user_id": string
          "conversation_id"?: string | null
          "title"?: string
          "html"?: string | null
          "created_at"?: string
          "project_id"?: string | null
          "message_id"?: string | null
          "raw"?: string
          "updated_at"?: string | null
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "conversation_id"?: string | null
          "title"?: string
          "html"?: string | null
          "created_at"?: string
          "project_id"?: string | null
          "message_id"?: string | null
          "raw"?: string
          "updated_at"?: string | null
        }
        Relationships: [
          {
  foreignKeyName: "artifacts_conversation_id_fkey"
  columns: ["conversation_id"]
  isOneToOne: false
  referencedRelation: "conversations"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "artifacts_conversation_message_fkey"
  columns: ["user_id","conversation_id","message_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["user_id","conversation_id","id"]
},
          {
  foreignKeyName: "artifacts_message_id_fkey"
  columns: ["message_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "artifacts_project_id_fkey"
  columns: ["project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "artifacts_tenant_conversation_fkey"
  columns: ["user_id","conversation_id"]
  isOneToOne: false
  referencedRelation: "conversations"
  referencedColumns: ["user_id","id"]
},
          {
  foreignKeyName: "artifacts_tenant_message_fkey"
  columns: ["user_id","message_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["user_id","id"]
},
          {
  foreignKeyName: "artifacts_tenant_project_fkey"
  columns: ["user_id","project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "audit_log": {
        Row: {
          "id": string
          "principal_id": string | null
          "actor_type": string
          "actor_id": string | null
          "action": string
          "resource_type": string
          "resource_id": string | null
          "job_id": string | null
          "request_id": string | null
          "metadata": Json
          "created_at": string
        }
        Insert: {
          "id"?: string
          "principal_id"?: string | null
          "actor_type": string
          "actor_id"?: string | null
          "action": string
          "resource_type": string
          "resource_id"?: string | null
          "job_id"?: string | null
          "request_id"?: string | null
          "metadata"?: Json
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "principal_id"?: string | null
          "actor_type"?: string
          "actor_id"?: string | null
          "action"?: string
          "resource_type"?: string
          "resource_id"?: string | null
          "job_id"?: string | null
          "request_id"?: string | null
          "metadata"?: Json
          "created_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "audit_log_job_id_fkey"
  columns: ["job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "audit_log_tenant_job_fkey"
  columns: ["principal_id","job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["principal_id","id"]
},
        ]
      },
      "billing_reconciliation_snapshots": {
        Row: {
          "singleton": boolean
          "generation": number
          "generated_at": string
          "healthy": boolean
          "metrics": Json
          "updated_at": string
        }
        Insert: {
          "singleton"?: boolean
          "generation"?: number
          "generated_at": string
          "healthy": boolean
          "metrics": Json
          "updated_at"?: string
        }
        Update: {
          "singleton"?: boolean
          "generation"?: number
          "generated_at"?: string
          "healthy"?: boolean
          "metrics"?: Json
          "updated_at"?: string
        }
        Relationships: []
      },
      "chat_generations": {
        Row: {
          "id": string
          "user_id": string
          "conversation_id": string
          "assistant_message_id": string
          "status": string
          "content": string
          "thinking": string
          "sequence": number
          "error": string | null
          "created_at": string
          "updated_at": string
          "cancel_requested_at": string | null
          "lease_owner": string | null
          "lease_expires_at": string | null
          "lease_version": number
          "media": Json
        }
        Insert: {
          "id": string
          "user_id": string
          "conversation_id": string
          "assistant_message_id": string
          "status"?: string
          "content"?: string
          "thinking"?: string
          "sequence"?: number
          "error"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "cancel_requested_at"?: string | null
          "lease_owner"?: string | null
          "lease_expires_at"?: string | null
          "lease_version"?: number
          "media"?: Json
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "conversation_id"?: string
          "assistant_message_id"?: string
          "status"?: string
          "content"?: string
          "thinking"?: string
          "sequence"?: number
          "error"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "cancel_requested_at"?: string | null
          "lease_owner"?: string | null
          "lease_expires_at"?: string | null
          "lease_version"?: number
          "media"?: Json
        }
        Relationships: [
          {
  foreignKeyName: "chat_generations_assistant_message_fkey"
  columns: ["assistant_message_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "chat_generations_conversation_id_fkey"
  columns: ["conversation_id"]
  isOneToOne: false
  referencedRelation: "conversations"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "chat_generations_tenant_assistant_message_fkey"
  columns: ["user_id","conversation_id","assistant_message_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["user_id","conversation_id","id"]
},
          {
  foreignKeyName: "chat_generations_tenant_conversation_fkey"
  columns: ["user_id","conversation_id"]
  isOneToOne: false
  referencedRelation: "conversations"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "code_memories": {
        Row: {
          "id": string
          "user_id": string
          "repo": string
          "content": string
          "created_at": string
        }
        Insert: {
          "id"?: string
          "user_id": string
          "repo": string
          "content": string
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "repo"?: string
          "content"?: string
          "created_at"?: string
        }
        Relationships: []
      },
      "code_messages": {
        Row: {
          "id": string
          "session_id": string
          "user_id": string
          "role": string
          "content": string
          "plan": Json | null
          "created_at": string
          "meta": Json | null
        }
        Insert: {
          "id"?: string
          "session_id": string
          "user_id": string
          "role": string
          "content"?: string
          "plan"?: Json | null
          "created_at"?: string
          "meta"?: Json | null
        }
        Update: {
          "id"?: string
          "session_id"?: string
          "user_id"?: string
          "role"?: string
          "content"?: string
          "plan"?: Json | null
          "created_at"?: string
          "meta"?: Json | null
        }
        Relationships: [
          {
  foreignKeyName: "code_messages_session_id_fkey"
  columns: ["session_id"]
  isOneToOne: false
  referencedRelation: "code_sessions"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "code_messages_tenant_session_fkey"
  columns: ["user_id","session_id"]
  isOneToOne: false
  referencedRelation: "code_sessions"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "code_sessions": {
        Row: {
          "id": string
          "user_id": string
          "repo": string
          "title": string
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "user_id": string
          "repo": string
          "title": string
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "repo"?: string
          "title"?: string
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: []
      },
      "conversation_chunks": {
        Row: {
          "id": string
          "user_id": string
          "conversation_id": string
          "project_id": string | null
          "conversation_title": string | null
          "message_start_id": string | null
          "message_end_id": string | null
          "content": string
          "content_hash": string
          "token_count": number
          "embedding": unknown
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "user_id": string
          "conversation_id": string
          "project_id"?: string | null
          "conversation_title"?: string | null
          "message_start_id"?: string | null
          "message_end_id"?: string | null
          "content": string
          "content_hash": string
          "token_count"?: number
          "embedding"?: unknown
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "conversation_id"?: string
          "project_id"?: string | null
          "conversation_title"?: string | null
          "message_start_id"?: string | null
          "message_end_id"?: string | null
          "content"?: string
          "content_hash"?: string
          "token_count"?: number
          "embedding"?: unknown
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "conversation_chunks_conversation_id_fkey"
  columns: ["conversation_id"]
  isOneToOne: false
  referencedRelation: "conversations"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "conversation_chunks_message_end_id_fkey"
  columns: ["message_end_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "conversation_chunks_message_start_id_fkey"
  columns: ["message_start_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "conversation_chunks_project_id_fkey"
  columns: ["project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "conversation_chunks_tenant_conversation_fkey"
  columns: ["user_id","conversation_id"]
  isOneToOne: false
  referencedRelation: "conversations"
  referencedColumns: ["user_id","id"]
},
          {
  foreignKeyName: "conversation_chunks_tenant_message_end_fkey"
  columns: ["user_id","conversation_id","message_end_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["user_id","conversation_id","id"]
},
          {
  foreignKeyName: "conversation_chunks_tenant_message_start_fkey"
  columns: ["user_id","conversation_id","message_start_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["user_id","conversation_id","id"]
},
          {
  foreignKeyName: "conversation_chunks_tenant_project_fkey"
  columns: ["user_id","project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "conversations": {
        Row: {
          "id": string
          "user_id": string
          "title": string
          "created_at": string
          "updated_at": string
          "project_id": string | null
          "starred": boolean
          "pinned": boolean
          "context_summary": string | null
          "summary_until_message_id": string | null
          "summary_token_count": number
        }
        Insert: {
          "id"?: string
          "user_id": string
          "title"?: string
          "created_at"?: string
          "updated_at"?: string
          "project_id"?: string | null
          "starred"?: boolean
          "pinned"?: boolean
          "context_summary"?: string | null
          "summary_until_message_id"?: string | null
          "summary_token_count"?: number
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "title"?: string
          "created_at"?: string
          "updated_at"?: string
          "project_id"?: string | null
          "starred"?: boolean
          "pinned"?: boolean
          "context_summary"?: string | null
          "summary_until_message_id"?: string | null
          "summary_token_count"?: number
        }
        Relationships: [
          {
  foreignKeyName: "conversations_project_id_fkey"
  columns: ["project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "conversations_summary_until_message_id_fkey"
  columns: ["summary_until_message_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "conversations_tenant_project_fkey"
  columns: ["user_id","project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["user_id","id"]
},
          {
  foreignKeyName: "conversations_tenant_summary_message_fkey"
  columns: ["user_id","id","summary_until_message_id"]
  isOneToOne: false
  referencedRelation: "messages"
  referencedColumns: ["user_id","conversation_id","id"]
},
        ]
      },
      "endpoints": {
        Row: {
          "id": string
          "user_id": string
          "name": string
          "protocol": string
          "base_url": string
          "api_key": string
          "model": string
          "output_kind": string
          "auth_type": string
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "user_id": string
          "name": string
          "protocol": string
          "base_url": string
          "api_key": string
          "model": string
          "output_kind"?: string
          "auth_type"?: string
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "name"?: string
          "protocol"?: string
          "base_url"?: string
          "api_key"?: string
          "model"?: string
          "output_kind"?: string
          "auth_type"?: string
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: []
      },
      "generated_media_cleanup_jobs": {
        Row: {
          "object_key": string
          "user_id": string
          "conversation_id": string
          "generation_id": string
          "reason": string
          "attempts": number
          "last_error": string | null
          "created_at": string
          "updated_at": string
          "completed_at": string | null
        }
        Insert: {
          "object_key": string
          "user_id": string
          "conversation_id": string
          "generation_id": string
          "reason": string
          "attempts"?: number
          "last_error"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "completed_at"?: string | null
        }
        Update: {
          "object_key"?: string
          "user_id"?: string
          "conversation_id"?: string
          "generation_id"?: string
          "reason"?: string
          "attempts"?: number
          "last_error"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "completed_at"?: string | null
        }
        Relationships: []
      },
      "github_connections": {
        Row: {
          "connection_id": string
          "user_id": string
          "github_user_id": number
          "login": string
          "credential_ciphertext": string
          "scopes": string[]
          "expires_at": string | null
          "connected_at": string
          "updated_at": string
          "last_used_at": string | null
        }
        Insert: {
          "connection_id"?: string
          "user_id": string
          "github_user_id": number
          "login": string
          "credential_ciphertext": string
          "scopes"?: string[]
          "expires_at"?: string | null
          "connected_at"?: string
          "updated_at"?: string
          "last_used_at"?: string | null
        }
        Update: {
          "connection_id"?: string
          "user_id"?: string
          "github_user_id"?: number
          "login"?: string
          "credential_ciphertext"?: string
          "scopes"?: string[]
          "expires_at"?: string | null
          "connected_at"?: string
          "updated_at"?: string
          "last_used_at"?: string | null
        }
        Relationships: []
      },
      "invitation_codes": {
        Row: {
          "id": string
          "code": string
          "tokens": number
          "created_by": string | null
          "used_by": string | null
          "created_at": string
          "used_at": string | null
        }
        Insert: {
          "id"?: string
          "code": string
          "tokens"?: number
          "created_by"?: string | null
          "used_by"?: string | null
          "created_at"?: string
          "used_at"?: string | null
        }
        Update: {
          "id"?: string
          "code"?: string
          "tokens"?: number
          "created_by"?: string | null
          "used_by"?: string | null
          "created_at"?: string
          "used_at"?: string | null
        }
        Relationships: []
      },
      "job_admission_reservations": {
        Row: {
          "job_id": string
          "principal_id": string
          "sku": string
          "price_version": number
          "funding": string
          "status": string
          "reserved_tokens": number
          "reserved_cost_micros": number
          "actual_tokens": number
          "actual_cost_micros": number
          "released_tokens": number
          "release_reason": string | null
          "created_at": string
          "expires_at": string
          "settled_at": string | null
          "price_quote": Json
          "price_quote_hash": string
        }
        Insert: {
          "job_id": string
          "principal_id": string
          "sku": string
          "price_version": number
          "funding": string
          "status"?: string
          "reserved_tokens": number
          "reserved_cost_micros": number
          "actual_tokens"?: number
          "actual_cost_micros"?: number
          "released_tokens"?: number
          "release_reason"?: string | null
          "created_at"?: string
          "expires_at": string
          "settled_at"?: string | null
          "price_quote": Json
          "price_quote_hash": string
        }
        Update: {
          "job_id"?: string
          "principal_id"?: string
          "sku"?: string
          "price_version"?: number
          "funding"?: string
          "status"?: string
          "reserved_tokens"?: number
          "reserved_cost_micros"?: number
          "actual_tokens"?: number
          "actual_cost_micros"?: number
          "released_tokens"?: number
          "release_reason"?: string | null
          "created_at"?: string
          "expires_at"?: string
          "settled_at"?: string | null
          "price_quote"?: Json
          "price_quote_hash"?: string
        }
        Relationships: [
          {
  foreignKeyName: "job_admission_reservations_job_fk"
  columns: ["job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "job_admission_reservations_price_fk"
  columns: ["sku","price_version"]
  isOneToOne: false
  referencedRelation: "job_price_catalog"
  referencedColumns: ["sku","version"]
},
          {
  foreignKeyName: "job_admission_reservations_tenant_job_fkey"
  columns: ["principal_id","job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["principal_id","id"]
},
        ]
      },
      "job_assets": {
        Row: {
          "id": string
          "job_id": string
          "principal_id": string
          "bucket": string
          "object_key": string
          "media_type": string
          "mime_type": string
          "bytes": number
          "state": string
          "lease_version": number
          "created_at": string
          "updated_at": string
          "canonical_at": string | null
          "deleted_at": string | null
        }
        Insert: {
          "id"?: string
          "job_id": string
          "principal_id": string
          "bucket": string
          "object_key": string
          "media_type": string
          "mime_type": string
          "bytes": number
          "state"?: string
          "lease_version": number
          "created_at"?: string
          "updated_at"?: string
          "canonical_at"?: string | null
          "deleted_at"?: string | null
        }
        Update: {
          "id"?: string
          "job_id"?: string
          "principal_id"?: string
          "bucket"?: string
          "object_key"?: string
          "media_type"?: string
          "mime_type"?: string
          "bytes"?: number
          "state"?: string
          "lease_version"?: number
          "created_at"?: string
          "updated_at"?: string
          "canonical_at"?: string | null
          "deleted_at"?: string | null
        }
        Relationships: [
          {
  foreignKeyName: "job_assets_job_id_fkey"
  columns: ["job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "job_assets_job_principal_fkey"
  columns: ["job_id","principal_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id","principal_id"]
},
        ]
      },
      "job_balance_movements": {
        Row: {
          "id": string
          "job_id": string
          "principal_id": string
          "ledger_entry_id": string | null
          "kind": string
          "tokens": number
          "created_at": string
        }
        Insert: {
          "id"?: string
          "job_id": string
          "principal_id": string
          "ledger_entry_id"?: string | null
          "kind": string
          "tokens": number
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "job_id"?: string
          "principal_id"?: string
          "ledger_entry_id"?: string | null
          "kind"?: string
          "tokens"?: number
          "created_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "job_balance_movements_job_fkey"
  columns: ["principal_id","job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["principal_id","id"]
},
          {
  foreignKeyName: "job_balance_movements_ledger_fkey"
  columns: ["principal_id","ledger_entry_id"]
  isOneToOne: false
  referencedRelation: "ledger_entries"
  referencedColumns: ["principal_id","id"]
},
        ]
      },
      "job_billing_cutovers": {
        Row: {
          "contract_version": number
          "cutover_at": string
          "legacy_nonterminal_jobs_at_cutover": number
          "created_at": string
        }
        Insert: {
          "contract_version": number
          "cutover_at": string
          "legacy_nonterminal_jobs_at_cutover": number
          "created_at"?: string
        }
        Update: {
          "contract_version"?: number
          "cutover_at"?: string
          "legacy_nonterminal_jobs_at_cutover"?: number
          "created_at"?: string
        }
        Relationships: []
      },
      "job_checkpoints": {
        Row: {
          "job_id": string
          "principal_id": string
          "version": number
          "phase": string
          "checkpoint": Json
          "progress": Json
          "resumable": boolean
          "lease_version": number
          "created_at": string
          "updated_at": string
          "commit_key": string | null
          "commit_attempt": number | null
          "commit_status": string | null
          "accounting_digest": string | null
        }
        Insert: {
          "job_id": string
          "principal_id": string
          "version"?: number
          "phase": string
          "checkpoint"?: Json
          "progress"?: Json
          "resumable"?: boolean
          "lease_version": number
          "created_at"?: string
          "updated_at"?: string
          "commit_key"?: string | null
          "commit_attempt"?: number | null
          "commit_status"?: string | null
          "accounting_digest"?: string | null
        }
        Update: {
          "job_id"?: string
          "principal_id"?: string
          "version"?: number
          "phase"?: string
          "checkpoint"?: Json
          "progress"?: Json
          "resumable"?: boolean
          "lease_version"?: number
          "created_at"?: string
          "updated_at"?: string
          "commit_key"?: string | null
          "commit_attempt"?: number | null
          "commit_status"?: string | null
          "accounting_digest"?: string | null
        }
        Relationships: [
          {
  foreignKeyName: "job_checkpoints_job_id_fkey"
  columns: ["job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "job_checkpoints_tenant_job_fkey"
  columns: ["principal_id","job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["principal_id","id"]
},
        ]
      },
      "job_events": {
        Row: {
          "id": string
          "job_id": string
          "principal_id": string
          "seq": number
          "kind": string
          "idempotency_key": string | null
          "schema_version": number
          "payload": Json
          "worker_id": string | null
          "lease_version": number | null
          "created_at": string
        }
        Insert: {
          "id"?: string
          "job_id": string
          "principal_id": string
          "seq": number
          "kind": string
          "idempotency_key"?: string | null
          "schema_version"?: number
          "payload"?: Json
          "worker_id"?: string | null
          "lease_version"?: number | null
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "job_id"?: string
          "principal_id"?: string
          "seq"?: number
          "kind"?: string
          "idempotency_key"?: string | null
          "schema_version"?: number
          "payload"?: Json
          "worker_id"?: string | null
          "lease_version"?: number | null
          "created_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "job_events_job_id_fkey"
  columns: ["job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "job_events_tenant_job_fkey"
  columns: ["principal_id","job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["principal_id","id"]
},
        ]
      },
      "job_observability_terminal_counts": {
        Row: {
          "job_type": string
          "status": string
          "total": number
          "updated_at": string
        }
        Insert: {
          "job_type": string
          "status": string
          "total"?: number
          "updated_at"?: string
        }
        Update: {
          "job_type"?: string
          "status"?: string
          "total"?: number
          "updated_at"?: string
        }
        Relationships: []
      },
      "job_outbox": {
        Row: {
          "id": string
          "job_id": string
          "principal_id": string
          "topic": string
          "dedupe_key": string
          "payload": Json
          "status": string
          "attempts": number
          "available_at": string
          "locked_by": string | null
          "lock_expires_at": string | null
          "published_at": string | null
          "last_error": string | null
          "created_at": string
          "updated_at": string
          "lock_version": number
          "max_attempts": number
          "replay_count": number
          "max_redrives": number
          "last_redrive_key": string | null
          "last_redrive_actor_id": string | null
          "last_redrive_from_lock_version": number | null
          "last_redriven_at": string | null
        }
        Insert: {
          "id"?: string
          "job_id": string
          "principal_id": string
          "topic": string
          "dedupe_key": string
          "payload"?: Json
          "status"?: string
          "attempts"?: number
          "available_at"?: string
          "locked_by"?: string | null
          "lock_expires_at"?: string | null
          "published_at"?: string | null
          "last_error"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "lock_version"?: number
          "max_attempts"?: number
          "replay_count"?: number
          "max_redrives"?: number
          "last_redrive_key"?: string | null
          "last_redrive_actor_id"?: string | null
          "last_redrive_from_lock_version"?: number | null
          "last_redriven_at"?: string | null
        }
        Update: {
          "id"?: string
          "job_id"?: string
          "principal_id"?: string
          "topic"?: string
          "dedupe_key"?: string
          "payload"?: Json
          "status"?: string
          "attempts"?: number
          "available_at"?: string
          "locked_by"?: string | null
          "lock_expires_at"?: string | null
          "published_at"?: string | null
          "last_error"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "lock_version"?: number
          "max_attempts"?: number
          "replay_count"?: number
          "max_redrives"?: number
          "last_redrive_key"?: string | null
          "last_redrive_actor_id"?: string | null
          "last_redrive_from_lock_version"?: number | null
          "last_redriven_at"?: string | null
        }
        Relationships: [
          {
  foreignKeyName: "job_outbox_job_id_fkey"
  columns: ["job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "job_outbox_job_principal_fkey"
  columns: ["job_id","principal_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id","principal_id"]
},
        ]
      },
      "job_payload_assets": {
        Row: {
          "job_id": string
          "principal_id": string
          "bucket": string
          "object_key": string
          "sha256": string
          "bytes": number
          "state": string
          "retain_until": string | null
          "created_at": string
          "updated_at": string
          "deleted_at": string | null
        }
        Insert: {
          "job_id": string
          "principal_id": string
          "bucket"?: string
          "object_key": string
          "sha256": string
          "bytes": number
          "state"?: string
          "retain_until"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "deleted_at"?: string | null
        }
        Update: {
          "job_id"?: string
          "principal_id"?: string
          "bucket"?: string
          "object_key"?: string
          "sha256"?: string
          "bytes"?: number
          "state"?: string
          "retain_until"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "deleted_at"?: string | null
        }
        Relationships: [
          {
  foreignKeyName: "job_payload_assets_job_principal_fkey"
  columns: ["job_id","principal_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id","principal_id"]
},
        ]
      },
      "job_price_activation_heads": {
        Row: {
          "sku": string
          "price_version": number
          "activation_generation": number
          "change_token": string
          "advanced_at": string
        }
        Insert: {
          "sku": string
          "price_version": number
          "activation_generation": number
          "change_token": string
          "advanced_at"?: string
        }
        Update: {
          "sku"?: string
          "price_version"?: number
          "activation_generation"?: number
          "change_token"?: string
          "advanced_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "job_price_activation_heads_price_fkey"
  columns: ["sku","price_version"]
  isOneToOne: false
  referencedRelation: "job_price_catalog"
  referencedColumns: ["sku","version"]
},
        ]
      },
      "job_price_activations": {
        Row: {
          "activation_id": number
          "sku": string
          "price_version": number
          "activation_generation": number
          "activated_at": string
          "activated_by": string
        }
        Insert: {
          "activation_id"?: never
          "sku": string
          "price_version": number
          "activation_generation"?: number
          "activated_at"?: string
          "activated_by"?: string
        }
        Update: {
          "activation_id"?: never
          "sku"?: string
          "price_version"?: number
          "activation_generation"?: number
          "activated_at"?: string
          "activated_by"?: string
        }
        Relationships: [
          {
  foreignKeyName: "job_price_activations_price_fkey"
  columns: ["sku","price_version"]
  isOneToOne: false
  referencedRelation: "job_price_catalog"
  referencedColumns: ["sku","version"]
},
        ]
      },
      "job_price_catalog": {
        Row: {
          "sku": string
          "version": number
          "default_reserve_tokens": number
          "raw_token_cap": number | null
          "token_multiplier_millis": number
          "reserve_cost_micros": number
          "currency": string
          "active": boolean
          "created_at": string
        }
        Insert: {
          "sku": string
          "version": number
          "default_reserve_tokens": number
          "raw_token_cap"?: number | null
          "token_multiplier_millis"?: number
          "reserve_cost_micros": number
          "currency"?: string
          "active"?: boolean
          "created_at"?: string
        }
        Update: {
          "sku"?: string
          "version"?: number
          "default_reserve_tokens"?: number
          "raw_token_cap"?: number | null
          "token_multiplier_millis"?: number
          "reserve_cost_micros"?: number
          "currency"?: string
          "active"?: boolean
          "created_at"?: string
        }
        Relationships: []
      },
      "job_stream_capacity_counters": {
        Row: {
          "scope": string
          "scope_key": string
          "active_count": number
          "updated_at": string
        }
        Insert: {
          "scope": string
          "scope_key": string
          "active_count": number
          "updated_at"?: string
        }
        Update: {
          "scope"?: string
          "scope_key"?: string
          "active_count"?: number
          "updated_at"?: string
        }
        Relationships: []
      },
      "job_stream_leases": {
        Row: {
          "id": string
          "principal_id": string
          "job_id": string
          "address_hash": string
          "acquired_at": string
          "expires_at": string
          "hard_expires_at": string
        }
        Insert: {
          "id": string
          "principal_id": string
          "job_id": string
          "address_hash": string
          "acquired_at"?: string
          "expires_at": string
          "hard_expires_at": string
        }
        Update: {
          "id"?: string
          "principal_id"?: string
          "job_id"?: string
          "address_hash"?: string
          "acquired_at"?: string
          "expires_at"?: string
          "hard_expires_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "job_stream_leases_job_principal_fkey"
  columns: ["job_id","principal_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id","principal_id"]
},
        ]
      },
      "job_tool_effects": {
        Row: {
          "id": string
          "job_id": string
          "principal_id": string
          "tool_call_id": string
          "tool_name": string
          "args_hash": string
          "effect_key": string
          "status": string
          "replay_safe": boolean
          "result_ref": Json | null
          "metadata": Json
          "lease_version": number
          "created_at": string
          "updated_at": string
          "completed_at": string | null
        }
        Insert: {
          "id"?: string
          "job_id": string
          "principal_id": string
          "tool_call_id": string
          "tool_name": string
          "args_hash": string
          "effect_key": string
          "status"?: string
          "replay_safe"?: boolean
          "result_ref"?: Json | null
          "metadata"?: Json
          "lease_version": number
          "created_at"?: string
          "updated_at"?: string
          "completed_at"?: string | null
        }
        Update: {
          "id"?: string
          "job_id"?: string
          "principal_id"?: string
          "tool_call_id"?: string
          "tool_name"?: string
          "args_hash"?: string
          "effect_key"?: string
          "status"?: string
          "replay_safe"?: boolean
          "result_ref"?: Json | null
          "metadata"?: Json
          "lease_version"?: number
          "created_at"?: string
          "updated_at"?: string
          "completed_at"?: string | null
        }
        Relationships: [
          {
  foreignKeyName: "job_tool_effects_job_id_fkey"
  columns: ["job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "job_tool_effects_tenant_job_fkey"
  columns: ["principal_id","job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["principal_id","id"]
},
        ]
      },
      "job_worker_heartbeats": {
        Row: {
          "worker_id": string
          "revision": string
          "queues": string[]
          "capacity": number
          "draining": boolean
          "started_at": string
          "heartbeat_at": string
          "queue_capacities": Json
        }
        Insert: {
          "worker_id": string
          "revision": string
          "queues": string[]
          "capacity": number
          "draining"?: boolean
          "started_at": string
          "heartbeat_at"?: string
          "queue_capacities"?: Json
        }
        Update: {
          "worker_id"?: string
          "revision"?: string
          "queues"?: string[]
          "capacity"?: number
          "draining"?: boolean
          "started_at"?: string
          "heartbeat_at"?: string
          "queue_capacities"?: Json
        }
        Relationships: []
      },
      "jobs": {
        Row: {
          "id": string
          "type": string
          "queue": string
          "principal_id": string
          "auth_class": string
          "subject": Json
          "idempotency_key": string
          "input_hash": string
          "payload": Json
          "budget": Json
          "status": string
          "attempt": number
          "max_attempts": number
          "priority": number
          "available_at": string
          "lease_owner": string | null
          "lease_version": number
          "lease_expires_at": string | null
          "cancel_requested_at": string | null
          "cancel_reason": string | null
          "progress": Json
          "result": Json | null
          "error_class": string | null
          "error_code": string | null
          "event_sequence": number
          "created_at": string
          "updated_at": string
          "started_at": string | null
          "terminal_at": string | null
          "confirmation_id": string | null
          "confirmation_plan_hash": string | null
          "authority_snapshot_id": string | null
          "authority_snapshot_digest": string | null
          "billing_contract_version": number
        }
        Insert: {
          "id": string
          "type": string
          "queue": string
          "principal_id": string
          "auth_class"?: string
          "subject"?: Json
          "idempotency_key": string
          "input_hash": string
          "payload"?: Json
          "budget"?: Json
          "status"?: string
          "attempt"?: number
          "max_attempts"?: number
          "priority"?: number
          "available_at"?: string
          "lease_owner"?: string | null
          "lease_version"?: number
          "lease_expires_at"?: string | null
          "cancel_requested_at"?: string | null
          "cancel_reason"?: string | null
          "progress"?: Json
          "result"?: Json | null
          "error_class"?: string | null
          "error_code"?: string | null
          "event_sequence"?: number
          "created_at"?: string
          "updated_at"?: string
          "started_at"?: string | null
          "terminal_at"?: string | null
          "confirmation_id"?: string | null
          "confirmation_plan_hash"?: string | null
          "authority_snapshot_id"?: string | null
          "authority_snapshot_digest"?: string | null
          "billing_contract_version"?: number
        }
        Update: {
          "id"?: string
          "type"?: string
          "queue"?: string
          "principal_id"?: string
          "auth_class"?: string
          "subject"?: Json
          "idempotency_key"?: string
          "input_hash"?: string
          "payload"?: Json
          "budget"?: Json
          "status"?: string
          "attempt"?: number
          "max_attempts"?: number
          "priority"?: number
          "available_at"?: string
          "lease_owner"?: string | null
          "lease_version"?: number
          "lease_expires_at"?: string | null
          "cancel_requested_at"?: string | null
          "cancel_reason"?: string | null
          "progress"?: Json
          "result"?: Json | null
          "error_class"?: string | null
          "error_code"?: string | null
          "event_sequence"?: number
          "created_at"?: string
          "updated_at"?: string
          "started_at"?: string | null
          "terminal_at"?: string | null
          "confirmation_id"?: string | null
          "confirmation_plan_hash"?: string | null
          "authority_snapshot_id"?: string | null
          "authority_snapshot_digest"?: string | null
          "billing_contract_version"?: number
        }
        Relationships: [
          {
  foreignKeyName: "jobs_confirmation_id_fkey"
  columns: ["confirmation_id"]
  isOneToOne: false
  referencedRelation: "agent_confirmation_gates"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "jobs_tenant_confirmation_fkey"
  columns: ["principal_id","confirmation_id"]
  isOneToOne: false
  referencedRelation: "agent_confirmation_gates"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "ledger_balance_settlements": {
        Row: {
          "ledger_entry_id": string
          "principal_id": string
          "requested_tokens": number
          "debited_tokens": number
          "remaining_balance": number
          "created_at": string
        }
        Insert: {
          "ledger_entry_id": string
          "principal_id": string
          "requested_tokens": number
          "debited_tokens": number
          "remaining_balance": number
          "created_at"?: string
        }
        Update: {
          "ledger_entry_id"?: string
          "principal_id"?: string
          "requested_tokens"?: number
          "debited_tokens"?: number
          "remaining_balance"?: number
          "created_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "ledger_balance_settlements_ledger_entry_id_fkey"
  columns: ["ledger_entry_id"]
  isOneToOne: false
  referencedRelation: "ledger_entries"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "ledger_balance_settlements_tenant_entry_fkey"
  columns: ["principal_id","ledger_entry_id"]
  isOneToOne: false
  referencedRelation: "ledger_entries"
  referencedColumns: ["principal_id","id"]
},
        ]
      },
      "ledger_entries": {
        Row: {
          "id": string
          "principal_id": string
          "job_id": string
          "idempotency_key": string
          "reason": string
          "direction": string
          "weighted_tokens": number
          "raw_tokens": number
          "model": string | null
          "provider": string | null
          "cost_estimate": number
          "currency": string
          "metadata": Json
          "created_at": string
        }
        Insert: {
          "id"?: string
          "principal_id": string
          "job_id": string
          "idempotency_key": string
          "reason": string
          "direction"?: string
          "weighted_tokens"?: number
          "raw_tokens"?: number
          "model"?: string | null
          "provider"?: string | null
          "cost_estimate"?: number
          "currency"?: string
          "metadata"?: Json
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "principal_id"?: string
          "job_id"?: string
          "idempotency_key"?: string
          "reason"?: string
          "direction"?: string
          "weighted_tokens"?: number
          "raw_tokens"?: number
          "model"?: string | null
          "provider"?: string | null
          "cost_estimate"?: number
          "currency"?: string
          "metadata"?: Json
          "created_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "ledger_entries_job_id_fkey"
  columns: ["job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "ledger_entries_tenant_job_fkey"
  columns: ["principal_id","job_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["principal_id","id"]
},
        ]
      },
      "memories": {
        Row: {
          "id": string
          "user_id": string
          "content": string
          "enabled": boolean
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "user_id": string
          "content": string
          "enabled"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "content"?: string
          "enabled"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: []
      },
      "messages": {
        Row: {
          "id": string
          "conversation_id": string
          "user_id": string
          "role": string
          "content": string
          "images": Json | null
          "thinking": string | null
          "created_at": string
          "seq": number
          "content_parts": Json
          "thinking_parts": Json
          "media_refs": Json
          "generation_id": string | null
          "status": string
          "identity_locked": boolean
          "content_hash": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "conversation_id": string
          "user_id": string
          "role": string
          "content"?: string
          "images"?: Json | null
          "thinking"?: string | null
          "created_at"?: string
          "seq": number
          "content_parts"?: Json
          "thinking_parts"?: Json
          "media_refs"?: Json
          "generation_id"?: string | null
          "status"?: string
          "identity_locked"?: boolean
          "content_hash": string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "conversation_id"?: string
          "user_id"?: string
          "role"?: string
          "content"?: string
          "images"?: Json | null
          "thinking"?: string | null
          "created_at"?: string
          "seq"?: number
          "content_parts"?: Json
          "thinking_parts"?: Json
          "media_refs"?: Json
          "generation_id"?: string | null
          "status"?: string
          "identity_locked"?: boolean
          "content_hash"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "messages_conversation_id_fkey"
  columns: ["conversation_id"]
  isOneToOne: false
  referencedRelation: "conversations"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "messages_generation_id_fkey"
  columns: ["generation_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "messages_tenant_conversation_fkey"
  columns: ["user_id","conversation_id"]
  isOneToOne: false
  referencedRelation: "conversations"
  referencedColumns: ["user_id","id"]
},
          {
  foreignKeyName: "messages_tenant_generation_fkey"
  columns: ["user_id","generation_id"]
  isOneToOne: false
  referencedRelation: "jobs"
  referencedColumns: ["principal_id","id"]
},
        ]
      },
      "profile_balance_anchors": {
        Row: {
          "principal_id": string
          "balance": number
          "anchored_at": string
        }
        Insert: {
          "principal_id": string
          "balance": number
          "anchored_at"?: string
        }
        Update: {
          "principal_id"?: string
          "balance"?: number
          "anchored_at"?: string
        }
        Relationships: []
      },
      "profile_balance_journal": {
        Row: {
          "sequence": number
          "principal_id": string
          "delta_tokens": number
          "balance_before": number
          "balance_after": number
          "source": string
          "transaction_id": number
          "created_at": string
        }
        Insert: {
          "sequence"?: never
          "principal_id": string
          "delta_tokens": number
          "balance_before": number
          "balance_after": number
          "source": string
          "transaction_id"?: number
          "created_at"?: string
        }
        Update: {
          "sequence"?: never
          "principal_id"?: string
          "delta_tokens"?: number
          "balance_before"?: number
          "balance_after"?: number
          "source"?: string
          "transaction_id"?: number
          "created_at"?: string
        }
        Relationships: []
      },
      "profiles": {
        Row: {
          "user_id": string
          "memory_enabled": boolean
          "custom_system_prompt": string | null
          "tokens_5h": number
          "window_5h_start": string | null
          "tokens_7d": number
          "window_7d_start": string | null
          "quota_version": number
          "balance": number
          "pool_5h_used": number
          "pool_5h_reset_at": string | null
          "pool_week_used": number
          "pool_week_reset_at": string | null
          "limit_5h": number | null
          "limit_week": number | null
          "created_at": string
        }
        Insert: {
          "user_id": string
          "memory_enabled"?: boolean
          "custom_system_prompt"?: string | null
          "tokens_5h"?: number
          "window_5h_start"?: string | null
          "tokens_7d"?: number
          "window_7d_start"?: string | null
          "quota_version"?: number
          "balance"?: number
          "pool_5h_used"?: number
          "pool_5h_reset_at"?: string | null
          "pool_week_used"?: number
          "pool_week_reset_at"?: string | null
          "limit_5h"?: number | null
          "limit_week"?: number | null
          "created_at"?: string
        }
        Update: {
          "user_id"?: string
          "memory_enabled"?: boolean
          "custom_system_prompt"?: string | null
          "tokens_5h"?: number
          "window_5h_start"?: string | null
          "tokens_7d"?: number
          "window_7d_start"?: string | null
          "quota_version"?: number
          "balance"?: number
          "pool_5h_used"?: number
          "pool_5h_reset_at"?: string | null
          "pool_week_used"?: number
          "pool_week_reset_at"?: string | null
          "limit_5h"?: number | null
          "limit_week"?: number | null
          "created_at"?: string
        }
        Relationships: []
      },
      "project_files": {
        Row: {
          "id": string
          "project_id": string
          "user_id": string
          "name": string
          "content": string
          "created_at": string
        }
        Insert: {
          "id"?: string
          "project_id": string
          "user_id": string
          "name": string
          "content"?: string
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "project_id"?: string
          "user_id"?: string
          "name"?: string
          "content"?: string
          "created_at"?: string
        }
        Relationships: [
          {
  foreignKeyName: "project_files_project_id_fkey"
  columns: ["project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "project_files_tenant_project_fkey"
  columns: ["user_id","project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "project_memories": {
        Row: {
          "id": string
          "user_id": string
          "project_id": string
          "content": string
          "created_at": string
          "updated_at": string | null
        }
        Insert: {
          "id"?: string
          "user_id": string
          "project_id": string
          "content": string
          "created_at"?: string
          "updated_at"?: string | null
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "project_id"?: string
          "content"?: string
          "created_at"?: string
          "updated_at"?: string | null
        }
        Relationships: [
          {
  foreignKeyName: "project_memories_project_id_fkey"
  columns: ["project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["id"]
},
          {
  foreignKeyName: "project_memories_tenant_project_fkey"
  columns: ["user_id","project_id"]
  isOneToOne: false
  referencedRelation: "projects"
  referencedColumns: ["user_id","id"]
},
        ]
      },
      "projects": {
        Row: {
          "id": string
          "user_id": string
          "name": string
          "instructions": string
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "user_id": string
          "name"?: string
          "instructions"?: string
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "user_id"?: string
          "name"?: string
          "instructions"?: string
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: []
      },
      "schema_contract_attestations": {
        Row: {
          "contract_version": number
          "manifest_sha256": string
          "migration_count": number
          "attested_at": string
        }
        Insert: {
          "contract_version": number
          "manifest_sha256": string
          "migration_count": number
          "attested_at"?: string
        }
        Update: {
          "contract_version"?: number
          "manifest_sha256"?: string
          "migration_count"?: number
          "attested_at"?: string
        }
        Relationships: []
      },
      "tenant_resource_usage": {
        Row: {
          "principal_id": string
          "project_file_count": number
          "project_file_bytes": number
          "message_count": number
          "message_bytes": number
          "payload_count": number
          "payload_bytes": number
          "updated_at": string
        }
        Insert: {
          "principal_id": string
          "project_file_count"?: number
          "project_file_bytes"?: number
          "message_count"?: number
          "message_bytes"?: number
          "payload_count"?: number
          "payload_bytes"?: number
          "updated_at"?: string
        }
        Update: {
          "principal_id"?: string
          "project_file_count"?: number
          "project_file_bytes"?: number
          "message_count"?: number
          "message_bytes"?: number
          "payload_count"?: number
          "payload_bytes"?: number
          "updated_at"?: string
        }
        Relationships: []
      },
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      "acquire_job_event_stream": { Args: { "input_stream_id": string | null; "input_principal_id": string | null; "input_job_id": string | null; "input_address_hash": string | null; "input_lease_seconds"?: number | null; "input_max_seconds"?: number | null }; Returns: Json }
      "adjust_tenant_resource_usage": { Args: { "input_principal_id": string | null; "input_project_file_count"?: number | null; "input_project_file_bytes"?: number | null; "input_message_count"?: number | null; "input_message_bytes"?: number | null; "input_payload_count"?: number | null; "input_payload_bytes"?: number | null }; Returns: undefined }
      "advance_agent_workspace_head": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_snapshot_id": string | null; "input_manifest_digest": string | null; "input_tree_digest": string | null; "input_head": string | null }; Returns: Json }
      "agent_confirmation_result": { Args: { "input_gate": Database["public"]["Tables"]["agent_confirmation_gates"]["Row"] | null }; Returns: Json }
      "append_job_events": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_events": Json | null }; Returns: Json }
      "assert_agent_confirmation_actor": { Args: { "input_user_id": string | null }; Returns: undefined }
      "assert_job_budget": { Args: { "input_budget": Json | null }; Returns: undefined }
      "bind_agent_operation_repository": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_repo": string | null; "input_branch": string | null }; Returns: Json }
      "bind_agent_workspace_branch": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_agent_branch": string | null }; Returns: Json }
      "build_job_price_quote_v2": { Args: { "input_sku": string | null; "input_price_version": number | null; "input_default_reserve_tokens": number | null; "input_raw_token_cap": number | null; "input_token_multiplier_millis": number | null; "input_catalog_reserve_cost_micros": number | null; "input_currency": string | null; "input_funding": string | null; "input_billing_class": string | null; "input_authorized_tokens": number | null; "input_authorized_cost_micros": number | null }; Returns: Json }
      "cancel_chat_generation": { Args: { "input_generation_id": string | null; "input_user_id": string | null }; Returns: Json }
      "cancel_idle_agent_task": { Args: { "input_task_id": string | null }; Returns: Json }
      "cancel_job": { Args: { "input_job_id": string | null; "input_principal_id": string | null; "input_reason"?: string | null }; Returns: Json }
      "checkpoint_job": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_phase": string | null; "input_checkpoint": Json | null; "input_progress"?: Json | null; "input_resumable"?: boolean | null; "input_status"?: string | null }; Returns: Json }
      "checkpoint_job_primitive": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_phase": string | null; "input_checkpoint": Json | null; "input_progress"?: Json | null; "input_resumable"?: boolean | null; "input_status"?: string | null }; Returns: Json }
      "checkpoint_job_with_accounting": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_attempt": number | null; "input_expected_checkpoint_version": number | null; "input_checkpoint_key": string | null; "input_phase": string | null; "input_checkpoint": Json | null; "input_progress"?: Json | null; "input_resumable"?: boolean | null; "input_status"?: string | null; "input_ledger_entries"?: Json | null }; Returns: Json }
      "claim_agent_run": { Args: { "input_task_id": string | null; "input_run_id": string | null; "lease_seconds"?: number | null }; Returns: boolean }
      "claim_chat_generation": { Args: { "input_generation_id": string | null; "input_user_id": string | null; "input_conversation_id": string | null; "input_assistant_message_id": string | null; "input_runner_id": string | null; "lease_seconds"?: number | null }; Returns: Json }
      "claim_job_outbox": { Args: { "input_worker_id": string | null; "input_topics": string[] | null; "input_lock_seconds"?: number | null }; Returns: Json }
      "claim_next_job": { Args: { "input_worker_id": string | null; "input_queues"?: string[] | null; "input_lease_seconds"?: number | null }; Returns: Json }
      "complete_job_outbox": { Args: { "input_outbox_id": string | null; "input_worker_id": string | null; "input_lock_version": number | null; "input_succeeded": boolean | null; "input_error"?: string | null; "input_retry_seconds"?: number | null }; Returns: Json }
      "compute_billing_reconciliation_v1": { Args: never; Returns: Json }
      "consume_agent_confirmation_gate": { Args: { "input_user_id": string | null; "input_task_id": string | null; "input_confirmation_id": string | null; "input_operation": string | null; "input_plan_canonical": string | null; "input_token_sha256": string | null }; Returns: Json }
      "consume_api_rate_limit": { Args: { "input_key_hash": string | null; "input_limit": number | null; "input_window_ms": number | null }; Returns: { "allowed": boolean; "remaining": number; "retry_after_seconds": number }[] }
      "create_agent_confirmation_gate": { Args: { "input_user_id": string | null; "input_task_id": string | null; "input_operation": string | null; "input_risk_level": string | null; "input_title": string | null; "input_reason": string | null; "input_files": string[] | null; "input_plan_canonical": string | null; "input_token_sha256": string | null; "input_resume_status"?: string | null; "input_ttl_seconds"?: number | null }; Returns: Json }
      "create_agent_operation_confirmation": { Args: { "input_user_id": string | null; "input_task_id": string | null; "input_goal": string | null; "input_plan_canonical": string | null; "input_token_sha256": string | null; "input_title": string | null; "input_reason": string | null; "input_files"?: string[] | null }; Returns: Json }
      "delete_conversation_with_media_cleanup": { Args: { "p_user_id": string | null; "p_conversation_id": string | null; "p_object_keys"?: string[] | null }; Returns: number }
      "delete_github_connection": { Args: { "input_user_id": string | null; "input_connection_id": string | null; "input_actor_id": string | null; "input_request_id"?: string | null }; Returns: boolean }
      "delete_messages_with_media_cleanup": { Args: { "p_user_id": string | null; "p_message_ids": string[] | null; "p_object_keys"?: string[] | null }; Returns: number }
      "enqueue_agent_operation": { Args: { "input_user_id": string | null; "input_task_id": string | null; "input_confirmation_id": string | null; "input_operation": string | null; "input_plan_canonical": string | null; "input_token_sha256": string | null; "input_job_id": string | null; "input_auth_class": string | null; "input_idempotency_key": string | null; "input_input_hash": string | null; "input_payload": Json | null; "input_snapshot_id"?: string | null; "input_snapshot_digest"?: string | null }; Returns: Json }
      "enqueue_agent_task_job": { Args: { "input_user_id": string | null; "input_task_id": string | null; "input_goal": string | null; "input_repo": string | null; "input_session_id": string | null; "input_response_id": string | null; "input_user_message_id": string | null; "input_job_id": string | null; "input_auth_class": string | null; "input_idempotency_key": string | null; "input_input_hash": string | null; "input_payload": Json | null }; Returns: Json }
      "enqueue_chat_regeneration_v1": { Args: { "input_user_id": string | null; "input_conversation_id": string | null; "input_operation": string | null; "input_source_user_message_id": string | null; "input_target_assistant_message_id": string | null; "input_expected_tail_message_id": string | null; "input_user_content": string | null; "input_assistant_message_id": string | null; "input_job_id": string | null; "input_auth_class": string | null; "input_idempotency_key": string | null; "input_input_hash": string | null; "input_payload": Json | null; "input_budget": Json | null; "input_queue": string | null; "input_max_attempts": number | null; "input_cleanup_object_keys"?: string[] | null }; Returns: Json }
      "enqueue_chat_turn_v1": { Args: { "input_user_id": string | null; "input_conversation_id": string | null; "input_create_conversation": boolean | null; "input_project_id": string | null; "input_conversation_title": string | null; "input_user_message_id": string | null; "input_user_content": string | null; "input_user_images": Json | null; "input_user_created_at": string | null; "input_assistant_message_id": string | null; "input_job_id": string | null; "input_auth_class": string | null; "input_idempotency_key": string | null; "input_input_hash": string | null; "input_payload": Json | null; "input_budget": Json | null; "input_queue": string | null; "input_max_attempts": number | null }; Returns: Json }
      "enqueue_job": { Args: { "input_job_id": string | null; "input_type": string | null; "input_queue": string | null; "input_principal_id": string | null; "input_auth_class": string | null; "input_subject": Json | null; "input_idempotency_key": string | null; "input_input_hash"?: string | null; "input_payload"?: Json | null; "input_budget"?: Json | null; "input_priority"?: number | null; "input_max_attempts"?: number | null; "input_available_at"?: string | null }; Returns: Json }
      "fail_stale_chat_generation": { Args: { "input_generation_id": string | null; "input_user_id": string | null }; Returns: Json }
      "finalize_chat_generation": { Args: { "input_generation_id": string | null; "input_user_id": string | null; "input_runner_id": string | null; "input_lease_version": number | null; "input_status": string | null; "input_content": string | null; "input_thinking": string | null; "input_sequence": number | null; "input_error"?: string | null; "input_media"?: Json | null }; Returns: Json }
      "finalize_job": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_status": string | null; "input_result"?: Json | null; "input_error_class"?: string | null; "input_error_code"?: string | null; "input_ledger_entries"?: Json | null; "input_outbox"?: Json | null }; Returns: Json }
      "finish_job_asset_cleanup": { Args: { "input_outbox_id": string | null; "input_worker_id": string | null; "input_lock_version": number | null; "input_object_keys": string[] | null }; Returns: Json }
      "finish_job_payload_cleanup": { Args: { "input_outbox_id": string | null; "input_worker_id": string | null; "input_lock_version": number | null; "input_object_key": string | null }; Returns: Json }
      "gen_random_uuid": { Args: never; Returns: string }
      "get_agent_confirmation_gate": { Args: { "input_user_id": string | null; "input_task_id": string | null }; Returns: Json }
      "get_ledger_quota_status": { Args: { "input_principal_id": string | null }; Returns: Json }
      "github_connection_status": { Args: { "input_user_id": string | null; "input_connection_id": string | null; "input_actor_type": string | null; "input_actor_id": string | null; "input_purpose": string | null; "input_request_id"?: string | null }; Returns: { "connection_id": string; "user_id": string; "github_user_id": number; "login": string; "expires_at": string; "connected_at": string; "last_used_at": string }[] }
      "heartbeat_job_worker": { Args: { "input_worker_id": string | null; "input_revision": string | null; "input_queues": string[] | null; "input_capacity": number | null; "input_started_at": string | null; "input_draining"?: boolean | null }; Returns: Json }
      "heartbeat_job_worker_v2": { Args: { "input_worker_id": string | null; "input_revision": string | null; "input_queue_capacities": Json | null; "input_started_at": string | null; "input_draining"?: boolean | null }; Returns: Json }
      "job_contract_json": { Args: { "input_job": Database["public"]["Tables"]["jobs"]["Row"] | null }; Returns: Json }
      "job_observability_type": { Args: { "input_type": string | null; "input_queue": string | null; "input_payload": Json | null }; Returns: string }
      "job_price_quote_hash": { Args: { "input_quote": Json }; Returns: string }
      "mark_job_worker_draining": { Args: { "input_worker_id": string | null }; Returns: Json }
      "match_conversation_chunks": { Args: { "query_embedding": unknown; "match_user_id": string | null; "match_project_id"?: string | null; "match_count"?: number | null; "similarity_threshold"?: number | null }; Returns: { "id": string; "conversation_id": string; "conversation_title": string; "project_id": string; "message_start_id": string; "message_end_id": string; "content": string; "similarity": number; "created_at": string }[] }
      "match_conversation_chunks_text": { Args: { "query_text": string | null; "match_user_id": string | null; "match_project_id"?: string | null; "match_count"?: number | null }; Returns: { "id": string; "conversation_id": string; "conversation_title": string; "project_id": string; "message_start_id": string; "message_end_id": string; "content": string; "similarity": number; "created_at": string }[] }
      "merge_agent_run_state": { Args: { "input_task_id": string | null; "patch": Json | null }; Returns: Json }
      "merge_agent_task_meta": { Args: { "input_task_id": string | null; "patch"?: Json | null; "remove_keys"?: string[] | null }; Returns: Json }
      "mirror_chat_job_progress": { Args: { "input_job": Database["public"]["Tables"]["jobs"]["Row"] | null }; Returns: undefined }
      "mirror_chat_job_terminal": { Args: { "input_job": Database["public"]["Tables"]["jobs"]["Row"] | null }; Returns: undefined }
      "prepare_job_asset_cleanup": { Args: { "input_outbox_id": string | null; "input_worker_id": string | null; "input_lock_version": number | null }; Returns: Json }
      "prepare_job_payload_cleanup": { Args: { "input_outbox_id": string | null; "input_worker_id": string | null; "input_lock_version": number | null }; Returns: Json }
      "read_agent_operation_authority": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null }; Returns: Json }
      "read_billing_reconciliation_v1": { Args: never; Returns: Json }
      "read_github_connection": { Args: { "input_user_id": string | null; "input_connection_id": string | null; "input_actor_type": string | null; "input_actor_id": string | null; "input_purpose": string | null; "input_request_id"?: string | null }; Returns: { "connection_id": string; "user_id": string; "github_user_id": number; "login": string; "credential_ciphertext": string; "scopes": string[]; "expires_at": string }[] }
      "read_job_observability_v1": { Args: { "input_window_seconds"?: number | null }; Returns: Json }
      "read_job_worker_readiness_v1": { Args: { "input_required_queues"?: string[] | null; "input_max_age_seconds"?: number | null }; Returns: Json }
      "read_job_worker_readiness_v2": { Args: { "input_required_queues": string[] | null; "input_max_age_seconds": number | null; "input_revision": string | null }; Returns: Json }
      "read_job_worker_readiness_v3": { Args: { "input_required_queues": string[] | null; "input_max_age_seconds": number | null; "input_revision": string | null }; Returns: Json }
      "read_stream_lifecycle_metrics_v1": { Args: never; Returns: Json }
      "record_job_accounting": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_attempt": number | null; "input_ledger_entries": Json | null }; Returns: Json }
      "record_job_asset": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_principal_id": string | null; "input_bucket": string | null; "input_object_key": string | null; "input_media_type": string | null; "input_mime_type": string | null; "input_bytes": number | null; "input_state": string | null }; Returns: Json }
      "record_job_tool_effect": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_tool_call_id": string | null; "input_tool_name": string | null; "input_args_hash": string | null; "input_effect_key": string | null; "input_status": string | null; "input_result_ref"?: Json | null; "input_replay_safe"?: boolean | null; "input_metadata"?: Json | null }; Returns: Json }
      "record_quota_usage": { Args: { "weighted_tokens": number | null; "use_balance"?: boolean | null }; Returns: undefined }
      "redeem_invitation_code": { Args: { "input_code": string | null }; Returns: { "tokens_added": number; "new_balance": number }[] }
      "redrive_job_outbox": { Args: { "input_outbox_id": string | null; "input_expected_lock_version": number | null; "input_redrive_key": string | null; "input_actor_id": string | null; "input_reason": string | null; "input_delay_seconds"?: number | null }; Returns: Json }
      "refresh_billing_reconciliation_v1": { Args: never; Returns: Json }
      "release_agent_run": { Args: { "input_task_id": string | null; "input_run_id": string | null }; Returns: undefined }
      "release_job_admission_reservation": { Args: { "input_job_id": string | null; "input_reason"?: string | null }; Returns: Json }
      "release_job_event_stream": { Args: { "input_stream_id": string | null }; Returns: Json }
      "renew_agent_run": { Args: { "input_task_id": string | null; "input_run_id": string | null; "lease_seconds"?: number | null }; Returns: boolean }
      "renew_chat_generation_lease": { Args: { "input_generation_id": string | null; "input_user_id": string | null; "input_runner_id": string | null; "input_lease_version": number | null; "lease_seconds"?: number | null }; Returns: boolean }
      "renew_job_event_stream": { Args: { "input_stream_id": string | null; "input_lease_seconds"?: number | null }; Returns: Json }
      "renew_job_lease": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_lease_seconds"?: number | null }; Returns: Json }
      "renew_job_outbox": { Args: { "input_outbox_id": string | null; "input_worker_id": string | null; "input_lock_version": number | null; "input_lock_seconds"?: number | null }; Returns: Json }
      "resolve_agent_confirmation_gate": { Args: { "input_user_id": string | null; "input_task_id": string | null; "input_confirmation_id": string | null; "input_operation": string | null; "input_token_sha256": string | null; "input_action": string | null; "input_reason"?: string | null }; Returns: Json }
      "resume_awaiting_job": { Args: { "input_job_id": string | null; "input_principal_id": string | null; "input_expected_checkpoint_version": number | null; "input_idempotency_key": string | null; "input_resume_input": Json | null }; Returns: Json }
      "retry_job": { Args: { "input_job_id": string | null; "input_worker_id": string | null; "input_lease_version": number | null; "input_error_class": string | null; "input_error_code": string | null; "input_delay_seconds"?: number | null }; Returns: Json }
      "runtime_healthcheck": { Args: never; Returns: boolean }
      "runtime_healthcheck_v11": { Args: never; Returns: boolean }
      "runtime_healthcheck_v12": { Args: never; Returns: boolean }
      "runtime_healthcheck_v13": { Args: never; Returns: boolean }
      "runtime_healthcheck_v14": { Args: never; Returns: boolean }
      "runtime_healthcheck_v15": { Args: never; Returns: boolean }
      "runtime_healthcheck_v2": { Args: never; Returns: boolean }
      "runtime_healthcheck_v3": { Args: never; Returns: boolean }
      "runtime_healthcheck_v4": { Args: never; Returns: boolean }
      "runtime_healthcheck_v5": { Args: never; Returns: boolean }
      "runtime_healthcheck_v6": { Args: never; Returns: boolean }
      "runtime_healthcheck_v7": { Args: never; Returns: boolean }
      "runtime_healthcheck_v8": { Args: never; Returns: boolean }
      "settle_job_admission": { Args: { "input_job_id": string | null; "input_reason"?: string | null }; Returns: Json }
      "sweep_job_lifecycle": { Args: { "input_batch_size"?: number | null; "input_published_before"?: string | null }; Returns: Json }
      "upsert_github_connection": { Args: { "input_user_id": string | null; "input_github_user_id": number | null; "input_login": string | null; "input_credential_ciphertext": string | null; "input_scopes": string[] | null; "input_expires_at": string | null; "input_actor_id": string | null; "input_request_id"?: string | null }; Returns: string }
      "valid_job_worker_queue_capacities": { Args: { "input": Json }; Returns: boolean }
      "validate_github_connection_actor": { Args: { "input_user_id": string | null; "input_connection_id": string | null; "input_actor_type": string | null; "input_actor_id": string | null; "input_purpose": string | null; "input_request_id": string | null }; Returns: undefined }
      "verify_schema_contract_v1": { Args: { "input_contract_version": number; "input_manifest_sha256": string; "input_migration_count": number }; Returns: boolean }
      "verify_schema_contract_v2": { Args: { "input_contract_version": number; "input_manifest_sha256": string; "input_migration_count": number }; Returns: boolean }
      "write_chat_generation_progress": { Args: { "input_generation_id": string | null; "input_user_id": string | null; "input_runner_id": string | null; "input_lease_version": number | null; "input_content": string | null; "input_thinking": string | null; "input_sequence": number | null }; Returns: Json }
      "write_github_connection_audit": { Args: { "input_principal_id": string | null; "input_actor_type": string | null; "input_actor_id": string | null; "input_action": string | null; "input_resource_id": string | null; "input_request_id": string | null; "input_metadata": Json | null }; Returns: undefined }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database["public"]

export type Tables<TableName extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])> =
  (DefaultSchema["Tables"] & DefaultSchema["Views"])[TableName] extends { Row: infer Row }
    ? Row
    : never

export type TablesInsert<TableName extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][TableName] extends { Insert: infer Insert } ? Insert : never

export type TablesUpdate<TableName extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][TableName] extends { Update: infer Update } ? Update : never

export type Enums<EnumName extends keyof DefaultSchema["Enums"]> =
  DefaultSchema["Enums"][EnumName]

export type CompositeTypes<CompositeName extends keyof DefaultSchema["CompositeTypes"]> =
  DefaultSchema["CompositeTypes"][CompositeName]
